version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab_muaban_crawler
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 64M
    networks:
      - lab-network

networks:
  lab-network:
    external: true
