# 1. Chuyển hướng toàn bộ HTTP sang HTTPS
server {
    listen 80;
    server_name lab.nokanguyen.com;
    return 301 https://$host$request_uri;
}

# 2. Server block chính cho HTTPS (Port 443)
server {
    listen 443 ssl;
    http2 on;                  # Bật HTTP/2 tăng tốc độ load
    server_name lab.nokanguyen.com;

    ssl_certificate /etc/letsencrypt/live/lab.nokanguyen.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lab.nokanguyen.com/privkey.pem;

    # Tối ưu hóa bảo mật và cache SSL session
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    # Proxy tới container React frontend
    # location / {
    #     proxy_pass http://lab-frontend:80;
    #     proxy_set_header Host $host;
    #     proxy_set_header X-Real-IP $remote_addr;
    #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #     proxy_set_header X-Forwarded-Proto https;
    # }

    # Proxy cho các API microservice sau này (nếu có)
    location /api/ {
        proxy_pass http://lab-backend:9090/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
    }
}
