# -----------------------------
# Kết nối và Network
# -----------------------------
listen_addresses = '*'
max_connections = 50

# -----------------------------
# Quản lý Bộ nhớ (RAM)
# -----------------------------
# Dung lượng cache bộ nhớ dùng chung (thường 25% quota của container)
shared_buffers = 128MB

# Ước tính cache RAM tổng thể mà OS/DB có thể dùng
effective_cache_size = 384MB

# Bộ nhớ cho mỗi câu query sắp xếp/grouping phức tạp
work_mem = 4MB

# Bộ nhớ cho bảo trì, index, vacuum
maintenance_work_mem = 32MB

# -----------------------------
# Write-Ahead Logging (WAL)
# -----------------------------
wal_buffers = 4MB
checkpoint_completion_target = 0.9

# -----------------------------
# Ghi Log
# -----------------------------
log_timezone = 'UTC'
log_min_messages = warning
log_min_error_statement = error
